# Generated by Django 2.0.6 on 2020-03-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
        migrations.AlterModelTable(
            name='catagory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
