# Generated by Django 2.0.6 on 2020-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200328_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='index',
            field=models.IntegerField(default=999, verbose_name='分类的排序'),
        ),
    ]
