# Generated by Django 2.0.6 on 2020-03-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200329_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(upload_to='../media/upload')),
            ],
        ),
    ]
