# Generated by Django 2.0.6 on 2020-03-29 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPic',
        ),
    ]
