# Generated by Django 2.0.6 on 2020-03-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_blogpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='../media/head/user.png', max_length=200, upload_to='../media/head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
