# Generated by Django 2.0.6 on 2020-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200329_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to='../media/ad/%Y/%m', verbose_name='图片路径'),
        ),
    ]
