# Generated by Django 2.0.6 on 2020-03-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200329_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to='ad/%Y/%m', verbose_name='图片路径'),
        ),
    ]
