# Generated by Django 2.0.6 on 2020-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'ordering': ('index', 'name'), 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='index',
            field=models.IntegerField(default=900, unique=True, verbose_name='排列顺序（从小到大）'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='index',
            field=models.IntegerField(default=999, unique=True, verbose_name='分类的排序'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签名称'),
        ),
    ]
